repos:
  - repo: 'https://github.com/psf/black'
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - '--line-length=120'
        files: src
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - '--profile=black'
          - '--line-length=120'
        files: src
  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - '--max-line-length=120'
          - '--ignore=E203'
          - '--exclude=__init__.py'
        files: src
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.961
    hooks:
      - id: mypy
        args:
          - '--install-types'
          - '--non-interactive'
          - '--ignore-missing-imports'
        files: src
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: src